mapped ga3 client side events to ga4
littledata/shopify-tracker pull request #107
Opened 2020-11-19 10:34 UTC by fstefan7

2020-11-19 10:34 UTC, fstefan7 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Client side parameter mapping between GA3 and GA4](https://trello.com/c/aM7DNc1g/4279-client-side-parameter-mapping-between-ga3-and-ga4)

2020-11-19 12:29 UTC, edwardupton requested changes

2020-11-19 12:29 UTC, edwardupton commented on src/gaTracker/helpers.ts
> +			send_to: LittledataLayer.webPropertyID,
I think send_to is still needed with GA4: https://developers.google.com/analytics/devguides/collection/ga4/translate-events#if_you_currently_use_gtagjs

2020-11-19 12:29 UTC, edwardupton commented on src/gaTracker/helpers.ts
> +		gtag('event', 'view_item_list', {
In each case it is the event properties which are changing, not the name. So I would refactor to have a `getViewItemListProperties` function, which decides on the properties depending on `isGa4Format()`

2020-11-19 12:29 UTC, edwardupton commented on src/gaTracker/helpers.ts
> +			send_to: LittledataLayer.webPropertyID,
We should allow sending to BOTH GA3 and GA4. So if both webPropertyID and measurementID are in the data layer, send the same event to both.

2020-11-19 12:29 UTC, edwardupton commented on src/gaTracker/helpers.ts
> +	return LittledataLayer.webPropertyID && LittledataLayer.webPropertyID.includes('G-');
No, it should be called `LittledataLayer.measurementID` for consistency. Don't rely on parsing the string

2020-11-24 13:23 UTC, edwardupton approved these changes

2020-12-03 15:13 UTC, edwardupton approved these changes
convertProductsToGa4Format could really do with unit tests, but i'll approve this to add later

2020-12-03 15:22 UTC, fstefan7 commented
@edwardupton I'll add a card for adding unit tests for the mapping

2020-12-21 09:15 UTC, merged