use GA library when gtag throws an error for retrieving the clientId
littledata/shopify-tracker pull request #113
Opened 2020-12-15 12:53 UTC by fstefan7

2020-12-15 12:54 UTC, fstefan7 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[GA4 & UA] ga/segment tracker to use gtag.js API](https://trello.com/c/1fqkaqrS/4285-ga4-ua-ga-segment-tracker-to-use-gtagjs-api)

2020-12-15 15:22 UTC, edwardupton requested changes

2020-12-15 15:22 UTC, edwardupton commented on src/common/helpers.ts
> +				const tracker = window.ga.getAll()[0];
I think this will run into a problem where window.ga is a function but getAll() returns nothing.

It needs to wait 10ms for library, see https://github.com/littledata/shopify-tracker/pull/91/files

2020-12-16 11:44 UTC, edwardupton approved these changes

2020-12-16 11:44 UTC, merged