Get trackers
littledata/shopify-tracker pull request #209
Opened 2021-04-29 12:43 UTC by edwardupton

2021-05-05 12:42 UTC, lyykfi requested changes

2021-05-05 12:42 UTC, lyykfi commented on src/gaTracker/helpers.ts
> +	const trackers = window.ga && window.ga.getAll && window.ga.getAll();
window?.ga?.getAll?.()

2021-05-05 14:07 UTC, fstefan7 commented on src/gaTracker/helpers.ts
> +	const trackers = window.ga && window.ga.getAll && window.ga.getAll();
changed to use optional chaining

2021-05-05 15:32 UTC, lyykfi approved these changes

2021-05-06 10:40 UTC, ionescurares approved these changes

2021-05-06 10:40 UTC, merged