PD-274 Store IP in local storage
littledata/shopify-tracker pull request #210
Opened 2021-04-30 16:09 UTC by edwardupton

2021-05-04 12:37 UTC, lyykfi requested changes

2021-05-04 12:37 UTC, lyykfi commented on src/segmentTracker/helpers.ts
>  		httpRequest
I would suggest to isolate the logic to a special helper like AnonymizedIpResolve for example.

2021-05-05 12:44 UTC, lyykfi requested changes

2021-05-05 12:44 UTC, lyykfi commented on src/segmentTracker/helpers.ts
> +		httpRequest
what do you think to use async/await here?

2021-05-05 12:44 UTC, lyykfi commented on src/segmentTracker/helpers.ts
> +const anonymizedIpResolve = (standardContext: object) => {
I would rather suggest don't have standardContext here.
I guess anonymizedIpResolve  should return only IP which was resolved.

What do you think?

2021-05-05 12:51 UTC, edwardupton commented on src/segmentTracker/helpers.ts
> +		httpRequest
We've had bad experiences of using async/await with webpack. Best not to

2021-05-05 12:52 UTC, edwardupton commented on src/segmentTracker/helpers.ts
> +		httpRequest
Making it webpack compatible with async/await doubles the size of the minified code and makes debugging much harder

2021-05-05 12:52 UTC, lyykfi commented on src/segmentTracker/helpers.ts
> +		httpRequest
That is fine. Though, what was a problem?

2021-05-05 12:53 UTC, MihaiCernat commented on src/segmentTracker/helpers.ts
> +		httpRequest
yes, it messes up badly sometimes

2021-05-05 12:55 UTC, lyykfi commented on src/segmentTracker/helpers.ts
> +		httpRequest
Agree, let skip for now.

2021-05-05 13:07 UTC, MihaiCernat commented
> should we have reject here?

@lyykfi no, some tests are failing, checking now

2021-05-05 13:09 UTC, lyykfi requested changes

2021-05-05 13:09 UTC, lyykfi commented on src/segmentTracker/helpers.ts
> +				resolve({});
should we use reject here?

2021-05-05 13:09 UTC, lyykfi commented on test/segmentTracker/getContext.test.ts
> +	it('does not call API if cached', async () => {
I think we should add a test for reject state.

2021-05-05 13:33 UTC, lyykfi approved these changes

2021-05-10 13:52 UTC, merged