Trust-Arc integration
littledata/shopify-tracker pull request #252
Opened 2021-06-14 12:53 UTC by edwardupton

2021-06-14 13:31 UTC, lyykfi commented
@edwardupton maybe we should change a target to merge to staging? also, i would suggest to change the default target from master to staging.

2021-06-14 14:00 UTC, edwardupton commented
@lyykfi No there is nothing to test on staging - this can only be tested once we have a link we can use with the customer, as we don't have access to TrustArc.

The alternative is to clone shopify-tracker repo into something like `ld-shopify-scripts` and push it only S3 from there.

2021-06-14 14:06 UTC, lyykfi requested changes

2021-06-14 14:06 UTC, lyykfi commented on src/customerPrivacyAPI/trustArc.ts
> +	const setTrackingConsent = (userCanBeTracked: boolean) =>
maybe just const setTrackingConsent = window.Shopify?.customerPrivacy?.setTrackingConsent; ?

2021-06-14 14:06 UTC, lyykfi commented on src/customerPrivacyAPI/trustArc.ts
> +				(decision = JSON.parse(event.data)) &&
I would suggest decision = JSON.parse(event.data) before if because parse could throw an error.

2021-06-14 14:14 UTC, edwardupton commented on src/customerPrivacyAPI/trustArc.ts
> +				(decision = JSON.parse(event.data)) &&
Can you clarify?

2021-06-14 14:17 UTC, edwardupton commented on src/customerPrivacyAPI/trustArc.ts
> +	const setTrackingConsent = (userCanBeTracked: boolean) =>
No, because I want to set a blank callback in all cases

2021-06-14 14:18 UTC, edwardupton commented on src/customerPrivacyAPI/trustArc.ts
> +			/** not a cm api message **/
No, this error means we shouldn't be handling the message

2021-06-14 14:19 UTC, lyykfi commented on src/customerPrivacyAPI/trustArc.ts
> +				(decision = JSON.parse(event.data)) &&
Sure. if a JSON in event.data is wrong somehow this JSON.parse(event.data) will throw en error. should we wrap it by try/catch or we don't expect any problems there?

2021-06-14 14:23 UTC, edwardupton commented
The whole if() is in a try/catch, so unecesssary

On Mon, Jun 14, 2021 at 3:19 PM Andrey ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/customerPrivacyAPI/trustArc.ts
> <https://github.com/littledata/shopify-tracker/pull/252#discussion_r650990657>
> :
>
> > +		}
> +	}, 50);
> +
> +	/*
> +    Callbacks will occur in the form of a PostMessage event.
> +    This code listens for the appropriately formatted PostMessage event,
> +    get's the new consent decision, and pushes the events into the GTM framework.
> +    Once the event is submitted, that consent decision is marked in the 'dispatched' map so it does not occur more than once.
> +   */
> +	self.addEventListener('message', function (event) {
> +		try {
> +			let decision;
> +
> +			if (
> +				event.data &&
> +				(decision = JSON.parse(event.data)) &&
>
> Sure. if a JSON in event.data is wrong somehow this JSON.parse(event.data)
> will throw en error. should we wrap it by try/catch or we don't expect any
> problems there?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/littledata/shopify-tracker/pull/252#discussion_r650990657>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAV6OKJOIKOAYY2MC4OD5TLTSYFYHANCNFSM46VFUUWA>
> .
>

2021-06-14 14:26 UTC, lyykfi commented
@edwardupton Looks good for me! However, should we add some tests here?

2021-06-14 14:28 UTC, lyykfi commented
@edwardupton Seems we don't have codeclimate connected here. Also, our codeship pipeline is poor. I'll create a card to code dept.

2021-06-14 14:32 UTC, edwardupton commented
Yes, we need test coverage for shopify-tracker.

For this particular feature, unit tests are hard because I can't find any
documentation on TrustArc's API

On Mon, Jun 14, 2021 at 3:28 PM Andrey ***@***.***> wrote:

> @edwardupton <https://github.com/edwardupton> Seems we don't have
> codeclimate connected here. Also, our codeship pipeline is poor. I'll
> create a card to code dept.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/littledata/shopify-tracker/pull/252#issuecomment-860730070>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAV6OKMDJX5AWCCLCGBG7B3TSYGZDANCNFSM46VFUUWA>
> .
>

2021-06-14 14:35 UTC, lyykfi commented
@edwardupton That is fine. however, that would be nice at least to mock function and detect that it was actually calling. what do you think?

2021-06-23 10:11 UTC, edwardupton commented
> @edwardupton That is fine. however, that would be nice at least to mock function and detect that it was actually calling. what do you think?

@lyykfi I spent half an hour on this, but since it's not my code the structure is hard to test. I was blocked trying to mock window.postMessage, as the code uses self.top.postMessage, which can't be easily injected.

This was only supposed to be a quick fix for one customer. I've added one test, but LMK if you think we can easily add more

2021-06-23 10:13 UTC, lyykfi commented
@edwardupton that is fine. thanks.

could you fix changing a dist folder again pls?

2021-06-23 11:51 UTC, edwardupton commented
> @edwardupton that is fine. thanks.
> 
> could you fix changing a dist folder again pls?

@lyykfi changed PR to staging.

2021-06-24 10:06 UTC, lyykfi approved these changes

2021-07-02 08:13 UTC, merged