PD-79 Consent tracking
littledata/shopify-tracker pull request #255
Opened 2021-06-17 13:42 UTC by edwardupton

2021-06-17 15:33 UTC, lyykfi requested changes

2021-06-17 15:33 UTC, lyykfi commented on index.d.ts
> +		//userDataCanBeSold: CallableFunction;
delete please.

2021-06-18 10:41 UTC, edwardupton commented on index.d.ts
> +		//userDataCanBeSold: CallableFunction;
@lyykfi fixed, review again

2021-06-18 10:43 UTC, lyykfi approved these changes

2021-06-18 15:15 UTC, merged