PD-532 Split out onetrust
littledata/shopify-tracker pull request #261
Opened 2021-06-23 11:22 UTC by edwardupton

2021-06-23 16:41 UTC, lyykfi requested changes

2021-06-23 16:41 UTC, lyykfi commented on src/customerPrivacyAPI/oneTrust.ts
> +	const interval = setInterval(function () {
should we have a deadline for the interval?

2021-06-23 16:41 UTC, lyykfi commented on src/customerPrivacyAPI/trustArc.ts
> +	const interval = setInterval(function () {
the same

2021-06-23 16:43 UTC, lyykfi commented
@edwardupton tests were waiting to long. I think we can restart them but in future we need to fix tests issues here.

2021-06-24 10:07 UTC, lyykfi commented
@edwardupton could you fix codeclimate please?

2021-06-24 10:08 UTC, lyykfi approved these changes

2021-06-24 10:11 UTC, edwardupton commented
@lyykfi fixed

2021-06-24 10:12 UTC, lyykfi commented
@edwardupton nice! thanks.

2021-06-29 13:31 UTC, lyykfi commented on src/customerPrivacyAPI/oneTrust.ts
> +import { CustomWindow } from '../..';
I think this file should be merged already to staging, isn't it?

2021-06-29 13:41 UTC, edwardupton commented on src/customerPrivacyAPI/oneTrust.ts
> +import { CustomWindow } from '../..';
Yes it used elsewhere

2021-06-29 16:52 UTC, lyykfi approved these changes

2021-07-02 08:13 UTC, merged