PD-631 - Facebook Pixel IDs
littledata/shopify-tracker pull request #285
Opened 2021-08-02 08:29 UTC by lageorgem

* Added logic for exctracting fbc and fbp cookies
* Added logic for storing said cookies into redis

2021-08-02 13:21 UTC, lyykfi requested changes

2021-08-02 13:21 UTC, lyykfi commented on src/segmentTracker/segmentTracker.ts
> +				const cookies = document.cookie
we already have 'getCookie' helper.

2021-08-02 13:21 UTC, lyykfi commented on index.d.ts
> +	fbq: any;
let keep it more specific.
fbq: {
loaded: boolean;
}

2021-08-02 13:28 UTC, lageorgem commented on src/segmentTracker/segmentTracker.ts
> +				const cookies = document.cookie
Done

2021-08-02 13:28 UTC, lageorgem commented on src/segmentTracker/segmentTracker.ts
> +				const cookies = document.cookie
Done

2021-08-02 13:28 UTC, lageorgem commented on index.d.ts
> +	fbq: any;
Done

2021-08-02 13:33 UTC, edwardupton commented on src/segmentTracker/segmentTracker.ts
> +			if (window?.fbq?.loaded) {
This should happen within window.analytics.ready callback, so we have a chance for FB library to add the cookie.

And can we import as a function like `retrieveAndStoreFacebookIds`? So this file stays clean

2021-08-02 13:36 UTC, lyykfi commented on src/segmentTracker/segmentTracker.ts
> +			if (window?.fbq?.loaded) {
@edwardupton we are talking about the same thing. :-)

2021-08-02 15:59 UTC, lyykfi commented on src/segmentTracker/segmentTracker.ts
> +			if (window?.fbq?.loaded) {
@lageorgem Just copy from a separated comment:

we do the same code twice here plus we don't isolate the FB logic from Segment.
I would suggest at least to add a helper file with functions to operate with FB or maybe a singletone class.

That could be like: FacebookCookieHelper.getItems(['_fbp', '_fbc'])

2021-08-03 08:04 UTC, lageorgem commented on src/segmentTracker/segmentTracker.ts
> +			if (window?.fbq?.loaded) {
@edwardupton I will move the logic separately, but I don't think we should wait for GA to load in order to get the facebook cookies. It's two separate scripts which probably load asynchronously. Is there a reason for that call in the analytics ready callback?

2021-08-03 08:16 UTC, edwardupton commented on src/segmentTracker/segmentTracker.ts
> +			if (window?.fbq?.loaded) {
@lageorgem this is not the callback for GA, but rather the callback for Segment.

We want to search for the cookies at the _latest time_ possible, to maximise the chance of FB library loading. There is no point sending fbc before the Segment library has loaded, because without the pageview the fbc value is useless.

Unfortunately there is no callback for `fbq`: https://stackoverflow.com/questions/29487133/facebook-conversion-event-callback

So I suggest it's better to fetch a bit later than earlier in the page load.

2021-08-03 08:18 UTC, edwardupton commented on src/segmentTracker/segmentTracker.ts
> +			if (window?.fbq?.loaded) {
Ah actually the solution is in `waitForGAtoLoad` function - we can check for existence of `fbq` with exponential back off - similar to what you have done, but keep trying.

2021-08-03 08:18 UTC, edwardupton commented on src/segmentTracker/segmentTracker.ts
> +			if (window?.fbq?.loaded) {
And yes, it doesn't need to be within analytics.ready callback.

2021-08-03 08:31 UTC, lageorgem commented on src/segmentTracker/segmentTracker.ts
> +			if (window?.fbq?.loaded) {
It's still a race condition. I added a timeout that checks every 50ms for window.fbq.loaded until it's loaded, but if it never loads the timeouts continue to check infinitely. There should be a better way to approach this.

2021-08-03 09:07 UTC, edwardupton commented on src/segmentTracker/segmentTracker.ts
> +			if (window?.fbq?.loaded) {
OK, it just needs unit tests then.

2021-08-03 09:21 UTC, lyykfi requested changes

2021-08-03 09:21 UTC, lyykfi commented on src/common/helpers.ts
> +	const fbpClientId = getCookie('_fbp').split('.').splice(2, 3).join('.');
I would suggest to have a separated function to parse cookies for FB.

parseFBCookieByName = (name) => {
const fbcClientId = getCookie(name).split('.').splice(2, 3).join('.');
}

2021-08-03 09:21 UTC, lyykfi commented on src/common/helpers.ts
> +	if (!window?.fbq?.loaded) {
could we have a generic function to track loading state like

const waitFor = (pattern, timeout = 50) => {
 return new Promise((resolve, reject) => {
   if (!pattern()) {
     setTimeout(waitFor , timeout );  
   } else {
    resolve()
   }
});
}

2021-08-03 12:12 UTC, lageorgem commented on src/segmentTracker/segmentTracker.ts
> +			if (window?.fbq?.loaded) {
Check it out

2021-08-03 12:12 UTC, lageorgem commented on src/common/helpers.ts
> +	const fbpClientId = getCookie('_fbp').split('.').splice(2, 3).join('.');
yes

2021-08-03 12:13 UTC, lageorgem commented on src/common/helpers.ts
> +	if (!window?.fbq?.loaded) {
Good old callback function solved it

2021-08-03 20:35 UTC, lyykfi approved these changes

2021-08-04 14:01 UTC, merged