PD 661 - GA4 Session
littledata/shopify-tracker pull request #290
Opened 2021-08-05 13:18 UTC by lageorgem

PD-661 GA4 Session ID

* Refactored waitForGaToLoad
* Saved GA measurementId cookie

2021-08-05 19:45 UTC, lyykfi requested changes

2021-08-05 19:45 UTC, lyykfi commented on src/common/helpers.ts
> +	const checkCallback: CheckCallback = () => {
That function can be moved from waitForGaToLoad because there isn't any dependencies. Also, it will fix codeclimate complains.

2021-08-05 19:45 UTC, lyykfi commented on src/common/helpers.ts
> +	const foundCallback: FoundCallback = (err: Error, trackers: any): void => {
the same.

2021-08-05 19:45 UTC, lyykfi commented on src/segmentTracker/helpers/retrieveAndStoreFacebookIds.ts
> +	const checkCallback: CheckCallback = () => window?.fbq?.loaded;
move out from the function.

2021-08-05 19:45 UTC, lyykfi commented on src/segmentTracker/helpers/retrieveAndStoreGA4Id.ts
> +		const [_, measurementId] = window.LittledataLayer.measurementId.split('-');
I am not sure but I guess you can write just [, measurementId]

2021-08-06 08:59 UTC, lageorgem commented on src/common/helpers.ts
> +	const checkCallback: CheckCallback = () => {
I did it because I found it to make more sense being inside the scope of the waitForGaToLoad. It would definetly work outside that function also, but i think it's harder to read this way.

2021-08-06 09:13 UTC, lyykfi commented on src/common/helpers.ts
> +	const checkCallback: CheckCallback = () => {
actually that could be a separated function with name 'getGATrackers()'. logically the function does separated thing.

2021-08-06 16:15 UTC, lageorgem commented on src/common/helpers.ts
> +	const foundCallback: FoundCallback = (err: Error, trackers: any): void => {
I'd rather keep the foundCallback inside the function, because it uses the callback provided as a parameter in the upper scope, and I find it cleaner to use that instead of passing it along.

2021-08-06 16:19 UTC, lyykfi approved these changes

2021-08-11 07:42 UTC, ionescurares approved these changes

2021-08-11 07:43 UTC, merged