FR-32 DPD-195 UTMs in segment payload
littledata/shopify-tracker pull request #374
Opened 2022-06-24 10:42 UTC by igorkol

2022-06-29 20:23 UTC, fstefan7 requested changes
Looks good, left a couple of comments.

2022-06-29 20:23 UTC, fstefan7 commented on src/common/constants.ts
> +export const UTM_ORDER_IN_ATTRIBUTES = ['utm_source', 'utm_medium', 'utm_campaign', 'utm_content', 'utm_term'];
I don't understand very well the name of this array, are we looking that the utm parameters to be in this order?

2022-06-29 20:23 UTC, fstefan7 commented on src/common/helpers/removeObjectProperties.ts
> +export const removeObjectPropertiesBasedOnValue = (removeValue: string, inputObj: LooseObject): LooseObject => {
Please add unit tests for this method as well

2022-06-29 20:23 UTC, fstefan7 commented on src/common/helpers/retrieveAndStoreUTMs.ts
> +	if (Object.keys(fullQueryObj).length === 0) return;
This is not needed, as 
```return Object.keys(fullQueryObj).filter((key) => key.includes('utm_'))```
treats this case as well

2022-06-29 20:23 UTC, fstefan7 commented on src/common/helpers/retrieveAndStoreUTMs.ts
> +const checkIfUtmsExist = (fullQueryObj: LooseObject): undefined | string[] => {
Here the name of the function is `checkIfUtmsExist` which in my mind(from its name) would throw an error if utms are not present, but instead it returns an array of utm keys. So it does not really check if utms exists

I suggest to change the name to something like `hasUtmParameters` and to return a boolean, true if it has any utm parameters and false otherwise

2022-06-29 20:23 UTC, fstefan7 commented on src/common/helpers/retrieveAndStoreUTMs.ts
> +const retrieveUTMs = (utmObj: LooseObject): undefined | LooseObject => {
Please add unit tests to the newly created methods

2022-06-29 20:23 UTC, fstefan7 commented on src/common/helpers/retrieveAndStoreUTMs.ts
> +			continue;
Instead of using `continue` you can add `arrayOfEntries.push(utms[key]);` inside an else branch. It would make the code a bit easier to read

2022-06-29 20:23 UTC, fstefan7 commented on src/segmentTracker/helpers/addUTMToEvents.ts
> +		return { ...properties };
This is the same as `return properties`

2022-06-29 20:23 UTC, fstefan7 commented on src/common/helpers/retrieveAndStoreUTMs.ts
> +			arrayOfEntries.push('empty');
I suggest pushing a falsy value, as `false` or `undefined`. In this case you can filter the object more easily with something as `[].filter(value => !!value)`

2022-06-30 06:34 UTC, igorkol commented on src/common/constants.ts
> +export const UTM_ORDER_IN_ATTRIBUTES = ['utm_source', 'utm_medium', 'utm_campaign', 'utm_content', 'utm_term'];
yes. i added the clarification in the filed

2022-06-30 19:16 UTC, igorkol commented on src/common/helpers/removeObjectProperties.ts
> +export const removeObjectPropertiesBasedOnValue = (removeValue: string, inputObj: LooseObject): LooseObject => {
done

2022-07-05 15:08 UTC, fstefan7 approved these changes
Looks nice! 👍

2022-07-05 15:08 UTC, fstefan7 commented on src/common/helpers/retrieveAndStoreUTMs.ts
> +		}
This if - else branch could be converted to:
```
const utmParameter = utms[key] || undefined; // the undefined here is not mandatory, only for being easier to understand
arrayOfEntries.push(utmParameter);
```

if you find it more readable

2022-07-06 11:29 UTC, merged