DPD-249 tracker npm with build
littledata/shopify-tracker pull request #377
Opened 2022-07-10 16:59 UTC by igorkol

2022-07-11 22:38 UTC, Getriax requested changes
I've changed the base to the branch it was derived from.

After addressing the review changes. We also need to change the circleci pipeline (introduce npm package build and publish workflow) - if you need help with that let me know.

2022-07-11 22:38 UTC, Getriax commented on index.js
> +		devtool: process.env.STAGE === 'prod' ? false : 'source-map',
I'd suggest going for another function parameter like `webpackOptions` that would have a value like `isProd` instead of relying on environment values. The builder can be run on different environments, that not necessarily have a `STAGE` env variable.

2022-07-11 22:38 UTC, Getriax commented on index.js
> +		devtool: process.env.STAGE === 'prod' ? false : 'source-map',
Also, what's with the formatting of that JSON. Looks like the prettier isn't working here? It's hard to read it.

2022-07-11 22:38 UTC, Getriax commented on index.js
> +	const webpack = require('webpack');
Let's move the imports to the top of the file, they don't have to be reinitialised with each function run.

2022-07-11 22:38 UTC, Getriax commented on index.js
> +/**
Since there is a chance we'll be using this builder with typescript, it would be nice to either make it `index.ts` with (requires tsc before building package) or at least to define `index.d.ts` that will export types definitions for that file.

2022-07-12 09:43 UTC, TheGame2500 requested changes
changes look ok, but you can't delete the dist folder, there are still old shops on manual depending on it.

2022-07-19 12:15 UTC, Getriax approved these changes
LGTM 🚀

2022-07-19 15:19 UTC, igorkol commented
@fstefan7 yes, but not dist files - just dist folder. files ended up in it only because i have tested something and then i erased them in some of the next pushes in the PR to clean that up

2022-07-19 15:19 UTC, igorkol commented on index.ts
> +		devtool: buildConfig.environment === 'development' ? 'source-map' : false,
resolved, thx

2022-08-01 09:18 UTC, merged