DPD-279 benchmarks
littledata/shopify-tracker pull request #379
Opened 2022-07-13 10:56 UTC by Getriax

https://littledata.atlassian.net/browse/DPD-279

2022-07-13 14:01 UTC, igorkol requested changes
some minor changes needed. otherwise it's okay

2022-07-13 14:01 UTC, igorkol commented on test/gaTracker/helpers.test.ts
> -		it('should send the email hashed to dL if customer object available');
please don't delete the file. it has a temporary placeholder role and is a reminder that we need to write a whole bunch of tests for the helpers.ts file

2022-07-15 09:47 UTC, Getriax commented on test/gaTracker/helpers.test.ts
> -		it('should send the email hashed to dL if customer object available');
Restored

2022-07-15 12:00 UTC, igorkol commented on src/gaTracker/helpers.ts
> +						{ event_label: network },
okay then. i suppose we can easily add it in when/if we see the data missing in the benchmarks

2022-07-15 12:05 UTC, igorkol approved these changes

2022-07-18 09:54 UTC, merged