DPD-251 | Add babel runtime packages
littledata/shopify-tracker pull request #387
Opened 2022-08-03 13:52 UTC by Getriax

2022-08-04 14:16 UTC, igorkol requested changes
@Getriax please review conflicts

2022-08-04 14:17 UTC, igorkol commented on package.json
> +		"@babel/runtime": "^7.18.9",
do we need this in the prod or can it be in the dev dependencies?

2022-08-05 11:29 UTC, TheGame2500 approved these changes

2022-08-18 15:04 UTC, igorkol approved these changes

2022-08-18 18:59 UTC, merged