DPD-251 | s3 upload
littledata/shopify-tracker pull request #392
Opened 2022-08-17 11:54 UTC by Getriax

2022-08-17 13:39 UTC, TheGame2500 approved these changes

2022-08-17 21:27 UTC, igorkol requested changes
generally, a very good code and a great change. only a few comments left

2022-08-17 21:27 UTC, igorkol commented on test/lib/bundleManager.test.ts
> +	it('Should generate bundle and upload the files to s3', async () => {
maybe have a few smaller tests instead of one big one? like one for generating bundle, one for creating and confirming the path, one for the upload...
that way, it would be easier to debug code and manage the tests in future

2022-08-17 21:27 UTC, igorkol commented on index.ts
>   * returns {Promise<BuildResult>} - { directory: directory where the scripts are present, filename: main file name }
it would be good if you could update the docs in the files that you changed (for ex. what build fn returns)

2022-08-17 21:27 UTC, igorkol commented on .circleci/config.yml
> +      - image: circleci/node:14
why did you have to bump the node version? what is the dependency?

2022-08-18 09:34 UTC, Getriax commented on .circleci/config.yml
> +      - image: circleci/node:14
It's an issue with `fs.promises.rm` which became available only with node v14. I could've used different approach to rm but since we use 14 already across all other server side services, this bump is not an issue.

2022-08-18 10:47 UTC, Getriax commented on test/lib/bundleManager.test.ts
> +	it('Should generate bundle and upload the files to s3', async () => {
We can do that, but this PR is not about adding tests, I only tested the stuff I added here which is s3 upload. The test has a few lines of code, but it's required here to check if multiple files are uploaded correctly.

2022-08-18 11:58 UTC, igorkol approved these changes

2022-08-18 14:30 UTC, merged