DPD-681/consent-states
littledata/shopify-tracker pull request #540
Opened 2023-07-12 12:38 UTC by SMihail

#### JIRA Issue: [DPD-681](https://littledata.atlassian.net/browse/DPD-681)

#### Changelog:
*

#### Checklist:
- [ ] I have tested my code locally and verified that it works
- [ ] I have written unit tests and e2e tests (if necessary)
- [ ] I have updated documentation, including necessary architectural schemas, and locally generated it for validation
- [ ] Code review was done by the following engineers:
- [ ] PR was validated to be ready to merge by the following QA engineer:

2023-07-20 11:48 UTC, lageorgem requested changes

2023-07-20 11:48 UTC, lageorgem commented on src/common/setClientID.ts
> +	const userAgent = window.navigator.userAgent;
This logic was moved under `collectUserProperties`. You don't need to collect user agent and IP in here anymore

2023-07-20 11:48 UTC, lageorgem commented on src/common/setClientID.ts
> +		const consent = calculateConsent(platform);
I don't think it's a good idea to use _up here, as it complicates the logic for client IDs in TMv2. Instead, I recommend creating a new client ID `_consent-clientID`, and set it in `getTrackingConsent`.

2023-07-20 11:48 UTC, lageorgem commented on src/common/setClientID.ts
> +		console.log(`[${session}] are we already posting to shopify?`, !!window.LittledataLayer.postingToShopify);
these logs were also removed, pls compare this file with staging

2023-07-20 11:48 UTC, lageorgem commented on src/segmentTracker/helpers.ts
> -			if (shouldAnonymize) {
why was this removed

2023-07-20 11:48 UTC, lageorgem commented on test/common/setClientID.test.ts
> +		getJSON.withArgs('//api.ipify.org?format=json').resolves({ ip: '127.0.0.1' });
after you implement my requested changes, i think it's safe to roll back this entire file. will probably help with your tests failing too

2023-07-20 13:05 UTC, SMihail commented on src/segmentTracker/helpers.ts
> -			if (shouldAnonymize) {
probably because of a bad merge, it got removed after i merged my branch with staging

2023-07-24 08:46 UTC, lageorgem commented on src/common/setClientID.ts
> +	const session = Math.floor(Math.random() * 1000);
Compare this file with staging, I think it should remain unchanged.

2023-07-24 08:46 UTC, lageorgem commented on src/segmentTracker/helpers.ts
> +				return resolve({ ip: ipFromStorage });
Compare this file with staging, it should be unchanged

2023-07-24 08:46 UTC, lageorgem commented on src/common/helpers/getTrackingConsent.ts
> +	if (tracker === 'segment') {
We should always report the consent, even in the edge cases above, as well as the isShopifyThankYou case. I suggest you take this out into a function that takes as parameter `tracker` and `forceConsent: boolean`

for `respectUserTrackingConsent: true`, `!window.Shopify` or `isShopifyThankYou: true`, you should call that function with `collectConsentCID(tracker, true)`

in `collectConsentCID`, if forceConsent = true, you should generate a fake yes instead of collecting `window.Shopify.customerPrivacy?.currentVisitorConsent?.()`

2023-07-24 10:03 UTC, lageorgem requested changes

2023-07-24 10:03 UTC, lageorgem commented on src/common/helpers/getTrackingConsent.ts
> +	if (tracker === 'segment') {
this if is no longer needed, you're doing the early return

2023-07-24 10:03 UTC, lageorgem commented on src/common/helpers/getTrackingConsent.ts
> +	if (!window.LittledataLayer.respectUserTrackingConsent || !window.Shopify || isShopifyThankYou) {
if you're going with this if, you don't need the forceConsent flag anymore

2023-07-24 10:03 UTC, lageorgem commented on src/common/helpers/getTrackingConsent.ts
> +		if (forceConsent) {
as said, forceConsent is no longer needed

2023-07-24 10:03 UTC, lageorgem commented on src/common/helpers/getTrackingConsent.ts
> +	collectConsentCID(tracker, true);
why? You're not handling these cases in your new code. do the `collectConsentCID` under each if, and leave the code as it was. `collectConsentCID` needs to be called before every `onConsentInput` call.

2023-07-24 14:31 UTC, lageorgem requested changes

2023-07-24 14:31 UTC, lageorgem commented on src/common/helpers/getTrackingConsent.ts
> +	);
```suggestion
	if (tracker !== 'segment') return;
	const isShopifyThankYou = window.Shopify?.Checkout?.page === shopifyPageTypes.thankYou;

	if (!window.LittledataLayer.respectUserTrackingConsent || !window.Shopify || isShopifyThankYou) {
		return {
			marketing: 'yes',
			analytics: 'yes',
			preferences: 'yes',
			sale_of_data: 'yes',
			gpc: 'yes',
		};
	}
	setClientID(window.Shopify.customerPrivacy?.currentVisitorConsent?.(), 'user_consent');
```

2023-07-27 11:34 UTC, lageorgem approved these changes

2023-08-03 08:10 UTC, lageorgem commented on src/common/helpers/getTrackingConsent.ts
> +			collectConsentCID(tracker);
this needs to be under the `if consent`

2023-08-03 08:10 UTC, lageorgem commented on src/common/helpers/getTrackingConsent.ts
> +			collectConsentCID(tracker);
and also before the onConsentInput from the `addEventListener` callback

2023-08-03 09:23 UTC, lageorgem approved these changes

2023-08-07 11:04 UTC, lageorgem requested changes

2023-08-07 11:04 UTC, lageorgem commented on src/common/helpers/getTrackingConsent.ts
> +	setClientID(window.Shopify.customerPrivacy?.currentVisitorConsent?.(), 'user_consent');
```suggestion
		setClientID(
			JSON.stringify({ marketing: 'yes', analytics: 'yes', preferences: 'yes', sale_of_data: 'yes', gpc: 'yes' }),
			'user_consent',
		);

		return;
	}
	setClientID(JSON.stringify(window.Shopify.customerPrivacy?.currentVisitorConsent?.() || {}), 'user_consent');
```

2023-08-29 09:02 UTC, merged