DPD-519/ga4-signup-event
littledata/shopify-tracker pull request #553
Opened 2023-08-01 10:15 UTC by SMihail

#### JIRA Issue: [519](https://littledata.atlassian.net/browse/DPD-519)

#### Changelog:
* track signup

#### Checklist:
- [x] I have tested my code locally and verified that it works
- [x] I have written unit tests and e2e tests (if necessary)
- [x] I have updated documentation, including necessary architectural schemas, and locally generated it for validation
- [x] Code review was done by the following engineers:
- [x] PR was validated to be ready to merge by the following QA engineer:

2023-08-01 10:50 UTC, lageorgem requested changes

2023-08-01 10:50 UTC, lageorgem commented on src/gaTracker/events/SignupEvent.ts
> +		await GoogleAnalyticsEventHandler.instance.sendEvent('register', {
event name should be [sign_up](https://developers.google.com/analytics/devguides/collection/protocol/ga4/reference/events#sign_up)

2023-08-01 10:50 UTC, lageorgem commented on src/gaTracker/events/SignupEvent.ts
> +		if (window.location.href.includes('account/register')) {
The registration flow is made more complicated by the confirmation email you receive. I think the algorithm should be as follows:

1. If we are on `account/register`, add the `localStorage` `registering`
2. if we are on `account/login`, remove the `localStorage` `registering` - indicating the user will instead opt for regular authentication
3. if the `localStorage` `registering` key exists AND `window.ShopifyAnalytics?.meta?.page?.customerId` is numeric, then it means that: 
    a) the user has authenticated since visiting the registration page
    b) the user hasn't gone through the `account/login` page - so likely they registered and then clicked the confirmation URL.

2023-08-01 12:26 UTC, SMihail commented on src/gaTracker/events/SignupEvent.ts
> +		await GoogleAnalyticsEventHandler.instance.sendEvent('register', {
https://developers.google.com/analytics/devguides/config/admin/v1/rest/v1alpha/accounts/provisionAccountTicket

`sign_up` or `provisionAccountTicket`? unclear from the admin api docs

2023-08-02 08:49 UTC, lageorgem commented on src/gaTracker/events/SignupEvent.ts
> +			window.sessionStorage.removeItem('ld_registered');
`sessionStorage` exists per browser tab, and is deleted when closing the browser. It doesn't survive like the auth cookie would. switch to `localStorage`

https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

2023-08-02 08:49 UTC, lageorgem commented on src/gaTracker/events/SignupEvent.ts
> +			window.sessionStorage.removeItem('ld_registered');
i think you should add this storage item on registering, not remove it. take a look at my previous comment again.

2023-08-02 08:53 UTC, lageorgem commented on src/gaTracker/events/SignupEvent.ts
> +		if ((isRegistered && isRegistered === 'true') || (isRegistered && typeof cid === 'number')) {
you probably don't need to do the early return like this here. I'd argue it's better to do something like this

```typescript
if (isRegistering && cid) { 
  return true 
}
```

Also pls change all `registered` to `registering`, since it's an ongoing state. The logic would be to mark the fact that the user has begun the registration process, and send the event when the user has actually logged in, with the exception being that you remove the `registering` state on the login page

2023-08-02 08:55 UTC, lageorgem commented on src/gaTracker/events/SignupEvent.ts
> +		await GoogleAnalyticsEventHandler.instance.sendEvent('register', {
sign_up

2023-08-02 12:31 UTC, lageorgem requested changes

2023-08-02 12:31 UTC, lageorgem commented on src/gaTracker/events/SignupEvent.ts
> +			return true;
no, event should not be triggered when we are on the register page. we only need to set the flag

2023-08-02 12:31 UTC, lageorgem commented on src/gaTracker/events/SignupEvent.ts
> +		window.localStorage.setItem('ld_registering', 'true');
not sure this is needed here

2023-08-02 12:31 UTC, lageorgem commented on src/gaTracker/events/SignupEvent.ts
> +			return false;
if the user is registering and we are authenticated, we **do not want** to trigger the event? change this to true

2023-08-02 12:31 UTC, lageorgem commented on src/gaTracker/events/SignupEvent.ts
> +		return true;
a default action should be do not trigger, so false

2023-08-03 07:47 UTC, lageorgem approved these changes

2023-08-08 10:29 UTC, lageorgem approved these changes

2023-08-09 13:03 UTC, merged