thank you page track
littledata/shopify-tracker pull request #65
Opened 2020-08-26 06:44 UTC by MihaiCernat

2020-08-26 06:46 UTC, MihaiCernat commented
![](https://github.trello.services/images/mini-trello-icon.png) [P1 || [Segment - Thank you page] Add pageview and event to Shopify order status / thank you page](https://trello.com/c/NZOGOMs7/4059-p1-segment-thank-you-page-add-pageview-and-event-to-shopify-order-status-thank-you-page)

2020-08-26 09:36 UTC, TheGame2500 requested changes
You also need to add a condition that this only runs if the current URL is the thank you page, otherwise this will run on all pages of the store

2020-08-26 09:36 UTC, TheGame2500 commented on src/gaThankYouPageTracker/gaThankYouPageTracker.ts
> +	const startIndex = scriptSrc.indexOf('webPropertId=');
@MihaiCernat I think there's a typo here. Should be `webPropertyId`

2020-08-26 09:36 UTC, TheGame2500 commented on src/segmentThankYouPageTracker/segmentThankYouPageTracker.ts
> +	const startIndexGa = scriptSrc.indexOf('webPropertId=');
@MihaiCernat same typo here

2020-08-26 09:36 UTC, TheGame2500 commented on src/gaThankYouPageTracker/gaThankYouPageTracker.ts
> +	const webPropertId = scriptSrc.subscting(startIndex + 14);
@MihaiCernat can we abstract getting the segmentProperty/webPropertyId in a function in helpers.ts?

2020-08-26 13:17 UTC, TheGame2500 approved these changes

2020-08-27 08:30 UTC, edwardupton requested changes

2020-08-27 08:30 UTC, edwardupton commented on src/gaThankYouPageTracker/gaThankYouPageTracker.ts
> +			event_label: 'Thank you',
Should be 'Thank you page'

2020-08-27 08:30 UTC, edwardupton commented on src/gaThankYouPageTracker/gaThankYouPageTracker.ts
> +			value: transaction_total,
Event values have to be integers, so round to nearest

2020-08-27 08:30 UTC, edwardupton commented on src/gaThankYouPageTracker/helpers.ts
> +export const getWebProperty = (scriptSrc: string): string => {
This isn't needed - you can use getProperties as a shared helper

2020-08-27 08:30 UTC, edwardupton commented on src/segmentThankYouPageTracker/segmentThankYouPageTracker.ts
> +		gtag('config', webPropertyId);
No, you don't need to init gtag for Segment - Segment already does that

2020-08-27 08:30 UTC, edwardupton commented on src/segmentThankYouPageTracker/segmentThankYouPageTracker.ts
> +		const analytics = (window.analytics = window.analytics || []);
There is already a helper for initializing Segment analyticsJS

2020-08-27 08:30 UTC, edwardupton commented on src/segmentThankYouPageTracker/segmentThankYouPageTracker.ts
> +		let gaClientId;
Not needed - Segment handles this

2020-08-27 08:30 UTC, edwardupton commented on src/segmentThankYouPageTracker/segmentThankYouPageTracker.ts
> +			integrations: {
Not needed - Segment handles this

2020-08-27 08:30 UTC, edwardupton commented on src/segmentThankYouPageTracker/segmentThankYouPageTracker.ts
> +				category: 'Shopify (Littledata)',
Not required

2020-08-27 08:30 UTC, edwardupton commented on src/segmentThankYouPageTracker/segmentThankYouPageTracker.ts
> +				presentment_total: checkout.total_price_set.presentment_money.amount,
Do you need to check for existence of total_price_set and presentment_money?

2020-08-27 08:30 UTC, edwardupton commented on src/segmentThankYouPageTracker/segmentThankYouPageTracker.ts
> +				products: products,
You need to translate fields into segmentProduct format

2020-08-27 21:23 UTC, edwardupton approved these changes

2020-09-02 12:13 UTC, merged